config/routes.rb
Rails.application.routes.draw do

  resources :absurdities,
            :format => :html,
            :only   => [:index, :show, :create]

end

app/controllers/absurdities_controller.rb
class AbsurditiesController < ApplicationController
  helper :absurdity
  layout "absurdities"

  def index
    @reports = Absurdity::Experiment.reports
  end

  def show
    @report = Absurdity::Experiment.find(params[:id].to_sym).report
  end

  def create
    Absurdity.track!(params[:metric], params[:experiment], params[:identity_id])
    render nothing: true
  end

end

app/helpers/absurdity_helper.rb
module AbsurdityHelper

  def metric_info(metrics, metric, count)
    content_tag(:span, "#{metric.to_s.humanize}: ", class: "metric")
    .concat "#{count} "
    # str += metric_ratios(metrics, metric, count)
  end

  def completed_text(completed)
    if completed == :completed
      content_tag(:span, "Completed")
    elsif completed
      content_tag(:span, "Completed: #{completed}")
    else
      ""
    end
  end

  private

  def metric_ratios(metrics, metric, count)
    ratios = metrics.map do |other_metric, other_count|
      if metric != other_metric && count != 0 && other_count != 0
        str = "#{metric.to_s.humanize}/#{other_metric.to_s.humanize} :"
        str += " #{number_to_percentage((count.to_f/other_count.to_f) * 100, precision: 3)}"
        str
      end
    end.compact
    ratios.present? ? "(" + ratios.join(",") + ")" : ""
  end
end

app/views/absurdities/index.html.erb
<header>
  <h1>Experiments</h1>
</header>

<ul class="reports">
<% @reports.each do |report| %>
  <li>
    <%= link_to report[:name].to_s.humanize, absurdity_path(report[:name]) %>
    <%= completed_text(report[:completed]) %>
  </li>
<% end %>
</ul>

app/views/absurdities/show.html.erb
<header>
  <h1>Experiment</h1>

  <h2>
    <%= @report[:name].to_s.humanize %>
  </h2>

  <h3>
    <%= completed_text(@report[:completed]) %>
  </h3>
</header>

<ul>
  <% @report[:data].each do |variant, metrics| %>
    <li class="variant">
      <h3><%= variant.to_s.humanize %></h3>
      <% metrics.each do |metric, count| %>
        <p><%= metric_info(metrics, metric, count) %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/absurdities.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>Absurdity - A/B Testing</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1, user-scalable=0">
    <link rel="apple-touch-icon" href="/images/iphone_favicon.png">
    <link rel="prev" href="/">

    <link rel="stylesheet" href="/stylesheets/absurdity.css" media="screen">
  </head>

  <body>
    <%= yield %>
  </body>

</html>